// export const authConstant = {
//   USER_LOGIN: "USER_LOGIN",
//   USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
//   USER_LOGOUT: "USER_LOGOUT",
//   USER_REGISTER: "USER_REGISTER",
//   USER_REGISTER_FAILED: "USER_REGISTER_FAILED",
//   SET_AUTH: "SET_AUTH",
//   ROLE_CREATE: "ROLE_CREATE",
//   USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
//   REMOVE_MESSAGE: "REMOVE_MESSAGE",
//   GET_ROLE_USER: "GET_ROLE_USER",
//   GET_ROLE_USER_FAILED: "GET_ROLE_USER_FAILED",
//   SET_ROLE_USER: "SET_ROLE_USER",
//   SET_ROLE_USER_FAILED: "SET_ROLE_USER_FAILED",
//   GET_USER_PROFILE: "GET_USER_PROFILE",
//   GET_USER_PROFILE_FAILED: "GET_USER_PROFILE_FAILED",
//   SET_USER_PROFILE: "SET_USER_PROFILE",
//   SET_AUTH_PROFILE: "SET_AUTH_PROFILE",
//   SET_AUTH_PROFILE_FAILED: "SET_AUTH_PROFILE_FAILED",
//   SET_USER_PROFILE_FAILED: "SET_USER_PROFILE_FAILED",
//   GET_MERITIAL_STATUS_SUCCESS: "GET_MERITIAL_STATUS_SUCCESS",
//   GET_MERITIAL_STATUS_FAILED: "GET_MERITIAL_STATUS_FAILED",
//   GET_USER_PROFILE_ADMIN: "GET_USER_PROFILE_ADMIN",
//   GET_USER_PROFILE_ADMIN_FAILED: "GET_USER_PROFILE_ADMIN_FAILED",
//   UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
//   UPDATE_USER_PROFILE_FAILED: "UPDATE_USER_PROFILE_FAILED",
// };

// export const PayerIdConstant = {
//   PAYER_ID_CONSTANT_SUCCESS: "PAYER_ID_CONSTANT_SUCCESS",
//   PAYER_ID_CONSTANT_FAILED: "PAYER_ID_CONSTANT_FAILED",
//   GET_PAYER_ID_CONSTANT_SUCCESS: "GET_PAYER_ID_CONSTANT_SUCCESS",
//   GET_PAYER_ID_CONSTANT_FAILED: "GET_PAYER_ID_CONSTANT_FAILED",
// };

// export const IndividualIdConstant = {
//   SET_INDIVIDUAL_PERSONAL_DETAIL: "SET_INDIVIDUAL_PERSONAL_DETAIL",
//   SET_INDIVIDUAL_PERSONAL_DETAIL_FAILED:
//     "SET_INDIVIDUAL_PERSONAL_DETAIL_FAILED",
//   SET_INDIVIDUAL_SPOUSE_DETAIL: "SET_INDIVIDUAL_SPOUSE_DETAIL",
//   SET_INDIVIDUAL_SPOUSE_DETAIL_FAILED: "SET_INDIVIDUAL_SPOUSE_DETAIL_FAILED",
//   GET_COUNTRY_DATA_SUCCESS: "GET_COUNTRY_DATA_SUCCESS",
//   GET_COUNTRY_DATA_FAILED: "GET_COUNTRY_DATA_FAILED",
//   GET_STATE_DATA_SUCCESS: "GET_STATE_DATA_SUCCESS",
//   GET_STATE_DATA_FAILED: "GET_STATE_DATA_FAILED",
//   GET_INDIVIDUAL_PERSONAL_SUCCESS: "GET_INDIVIDUAL_PERSONAL_SUCCESS",
//   GET_INDIVIDUAL_PERSONAL_FAILED: "GET_INDIVIDUAL_PERSONAL_FAILED",
//   UPDATE_DIRECTASSESSMENT_PERSONAL_SUCCESS:
//     "UPDATE_DIRECTASSESSMENT_PERSONAL_SUCCESS",
//   UPDATE_DIRECTASSESSMENT_PERSONAL_FAILED:
//     "UPDATE_DIRECTASSESSMENT_PERSONAL_FAILED",
//   INCOME_AND_CLAIMS_BASIC_DETAILS_SUCCESS:
//     "INCOME_AND_CLAIMS_BASIC_DETAILS_SUCCESS",
//   INCOME_AND_CLAIMS_BASIC_DETAILS_FAILED:
//     "INCOME_AND_CLAIMS_BASIC_DETAILS_FAILED",
//   INDIVIDUAL_PROPERTY_OWNERSHI_TYPE_MASTER_SUCCESS:
//     "INDIVIDUAL_PROPERTY_OWNERSHI_TYPE_MASTER_SUCCESS",
//   INDIVIDUAL_PROPERTY_OWNERSHI_TYPE_MASTER_FAILED:
//     "INDIVIDUAL_PROPERTY_OWNERSHI_TYPE_MASTER_FAILED",
//   GET_INDIVIDUAL_PROPERTY_OWNERSHI_TYPE_MASTER_SUCCESS:
//     "GET_INDIVIDUAL_PROPERTY_OWNERSHI_TYPE_MASTER_SUCCESS",
//   GET_INDIVIDUAL_PROPERTY_OWNERSHI_TYPE_MASTER_FAILED:
//     "GET_INDIVIDUAL_PROPERTY_OWNERSHI_TYPE_MASTER_FAILED",
//   UPDATE_INDIVIDUAL_PROPERTY_OWNERSHI_TYPE_MASTER_SUCCESS:
//     "UPDATE_INDIVIDUAL_PROPERTY_OWNERSHI_TYPE_MASTER_SUCCESS",
//   UPDATE_INDIVIDUAL_PROPERTY_OWNERSHI_TYPE_MASTER_FAILED:
//     "UPDATE_INDIVIDUAL_PROPERTY_OWNERSHI_TYPE_MASTER_FAILED",
//   DIRECT_ASSESSMENT_MANDATORY_DISCLOSURE_DETAILS_SUCCESS:
//     "DIRECT_ASSESSMENT_MANDATORY_DISCLOSURE_DETAILS_SUCCESS",
//   DIRECT_ASSESSMENT_MANDATORY_DISCLOSURE_DETAILS_FAILED:
//     "DIRECT_ASSESSMENT_MANDATORY_DISCLOSURE_DETAILS_FAILED",
//   DIRECT_ASSESSMENT_MANDATORY_DISCLOSURE_DETAILS_UPDATE_SUCCESS:
//     "DIRECT_ASSESSMENT_MANDATORY_DISCLOSURE_DETAILS_UPDATE_SUCCESS",
//   DIRECT_ASSESSMENT_MANDATORY_DISCLOSURE_DETAILS_UPDATE_FAILED:
//     "DIRECT_ASSESSMENT_MANDATORY_DISCLOSURE_DETAILS_UPDATE_FAILED",
//   DIRECT_ASSESSMENT_INDIVIDUAL_ALLOWANCES_DETAILS_SUCCESS:
//     "DIRECT_ASSESSMENT_INDIVIDUAL_ALLOWANCES_DETAILS_SUCCESS",
//   DIRECT_ASSESSMENT_INDIVIDUAL_ALLOWANCES_DETAILS_FAILED:
//     "DIRECT_ASSESSMENT_INDIVIDUAL_ALLOWANCES_DETAILS_FAILED",
//   DIRECT_ASSESSMENT_INDIVIDUAL_ALLOWANCES_DETAILS_UPDATE_SUCCESS:
//     "DIRECT_ASSESSMENT_INDIVIDUAL_ALLOWANCES_DETAILS_UPDATE_SUCCESS",
//   DIRECT_ASSESSMENT_INDIVIDUAL_ALLOWANCES_DETAILS_UPDATE_FAILED:
//     "DIRECT_ASSESSMENT_INDIVIDUAL_ALLOWANCES_DETAILS_UPDATE_FAILED"
// };

// export const EtccIndividualIdConstant = {
//   SET_ETCC_INDIVIDUAL_PERSONAL_DETAIL: "SET_ETCC_INDIVIDUAL_PERSONAL_DETAIL",
//   SET_ETCC_INDIVIDUAL_PERSONAL_DETAIL_FAILED:
//     "SET_ETCC_INDIVIDUAL_PERSONAL_DETAIL_FAILED",
//   SET_ETCC_INDIVIDUAL_SPOUSE_DETAIL: "SET_ETCC_INDIVIDUAL_SPOUSE_DETAIL",
//   SET_ETCC_INDIVIDUAL_SPOUSE_DETAIL_FAILED:
//     "SET_ETCC_INDIVIDUAL_SPOUSE_DETAIL_FAILED",
//   GET_COUNTRY_DATA_SUCCESS: "GET_COUNTRY_DATA_SUCCESS",
//   GET_COUNTRY_DATA_FAILED: "GET_COUNTRY_DATA_FAILED",
//   GET_STATE_DATA_SUCCESS: "GET_STATE_DATA_SUCCESS",
//   GET_STATE_DATA_FAILED: "GET_STATE_DATA_FAILED",
//   GET_ETCC_INDIVIDUAL_PERSONAL_SUCCESS: "GET_ETCC_INDIVIDUAL_PERSONAL_SUCCESS",
//   GET_ETCC_INDIVIDUAL_PERSONAL_FAILED: "GET_ETCC_INDIVIDUAL_PERSONAL_FAILED",
//   UPDATE_ETCC_INDIVIDUAL_PERSONAL_SUCCESS:
//     "UPDATE_ETCC_INDIVIDUAL_PERSONAL_SUCCESS",
//   UPDATE_ETCC_INDIVIDUAL_PERSONAL_FAILED:
//     "UPDATE_ETCC_INDIVIDUAL_PERSONAL_FAILED"
// };

// export const RaiseObjectionsIdConstant = {
//   SET_RAISE_OBJECTIONS_ID_CONSTANT_SUCCESS:
//     "RAISE_OBJECTIONS_ID_CONSTANT_SUCCESS",
//   SET_RAISE_OBJECTIONS_ID_CONSTANT_FAILED:
//     "RAISE_OBJECTIONS_ID_CONSTANT_FAILED",
//   GET_TAX_MASTER_STATION_SUCCESS: "GET_TAX_MASTER_STATION_SUCCESS",
//   GET_TAX_MASTER_STATION_FAILED: "GET_TAX_MASTER_STATION_FAILED",
// };

// export const BusinessPremisesConstant = {
//   SET_BUSINESS_PREMISES_CONSTANT_SUCCESS:
//     "SET_BUSINESS_PREMISES_CONSTANT_SUCCESS",
//   SET_BUSINESS_PREMISES_CONSTANT_FAILED:
//     "SET_BUSINESS_PREMISES_CONSTANT_FAILED",
// };

// export const DeploymentLevyConstant = {
//   SET_DEPLOYMENT_LEVY_CONSTANT_SUCCESS: "SET_DEPLOYMENT_LEVY_CONSTANT_SUCCESS",
//   SET_DEPLOYMENT_LEVY_CONSTANT_FAILED: "SET_DEPLOYMENT_LEVY_CONSTANT_FAILED",
// };

// export const YearMasterListConstant = {
//   GET_YEAR_DATA_SUCCESS: "GET_YEAR_DATA_SUCCESS",
//   GET_YEAR_DATA_FAILED: "GET_YEAR_DATA_FAILED"
// };
